---
- name: Install NPM packages for the client before building assets
  npm: path={{ client_path }}
       state=latest
       production=yes
  register: npm_client_install
  until: npm_client_install|success
  retries: 10
  delay: 30

- name: Clean up client build directory in order to get a fresh build
  file: path={{ item }}
        state=absent
  with_items:
    - "{{ client_path }}/dist"

- name: Build client assets
  command: npm run build
           chdir={{ client_path }}

- name: Set SELinux file type
  file: path="{{ client_path }}/dist"
        state=directory
        recurse=yes
        setype=httpd_sys_content_t
